### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by ThatNerdyPikachu**
lenny

### CODE REVIEW

**Comment by ghost** [comment]
"anybody but midou liscence"









i like it merge to master pls

**Comment by ThatNerdyPikachu** [comment]
yes pls

**Comment by ghost** [comment]
> [``](

- 

- [ ] lol

)

**Comment by superwhiskers** [comment]
this is also a gpl violation

**Comment by ThatNerdyPikachu** [comment]
Frick you

**Comment by midou360554** [comment]
...

**Comment by ThatNerdyPikachu** [comment]
rip

**Pull request closed without merging**
