### PR TITLE
fix typo 0w0 please merge

### PR DESCRIPTION
**Pull request by ghost**
fix a fucky wucky *starts twerking*

### CODE REVIEW

**Comment by ThatNerdyPikachu** [comment]
please kill yourself

**Comment by ghost** [comment]
please `show your vanadium silver iodine sodium`

**Comment by ghost** [comment]
[!ultra xd](https://did-you-know-that-the-last.letters-of-the-alphabet-are.xyz/dccv3qXN.png)

**Comment by midou360554** [comment]
oof

**Comment by Slick9000** [comment]
@superwhiskers can we like ban them from this repo

**Comment by ThatNerdyPikachu** [comment]
I agree

**Comment by anyputer** [comment]
self.die

**Comment by superwhiskers** [comment]
**no**

**Pull request closed without merging**
